import localFont from "next/font/local"
import type { Metadata } from "next"
import "./globals.css"
import Link from "next/link"
import { ModeToggle } from "@/components/mode-toggle"
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-2xl mx-auto py-10 px-4">
            <header className="flex items-center justify-between gap-6 md:gap-10">
              <Link href="/" className="flex items-center space-x-2">
                <span className="inline-block text-lg font-bold">
                  @hnsnml.co
                </span>
              </Link>
              <nav className="ml-auto space-x-6 font-medium">
                <Link href="/">Home</Link>
                <Link href="/about">About</Link>
              </nav>
              <ModeToggle />
            </header>
            <main>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
